FROM ghcr.io/deepflowys/rust-build:1.14 as builder
COPY .  /deepflow/
WORKDIR /deepflow/agent
ARG GITHUB_REF_NAME
RUN RUSTFLAGS="-D warnings" && cargo build --release && \
    cargo build --release --bin deepflow-agent-ctl && \
    ls -alh target/release
FROM scratch
COPY --from=builder /deepflow/agent/ /
